#version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app_network

#  db:
#    build:
#      context: .
#      dockerfile: Dockerfile-mysql
#    environment:
#      MYSQL_DATABASE: movie_db
#      MYSQL_ROOT_PASSWORD: mysql@121
#    ports:
#      - "3306:3306"
#    volumes:
#      - db_data:/var/lib/mysql
#    networks:
#      - app_network

  # MySQL Database
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysql@121
      MYSQL_DATABASE: movie_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
